### ISSUE TITLE
The recommended settings cannot fix the problem when using storybook

### ISSUE THREAD

**Issue by exKAZUu** [eddyerburgh/jest-transform-stub#1]
When using storybook,

```
  transform: {
    '^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
    // ... snip ...
  },
```

cannot fix the problem (`Syntax Error: Invalid or unexpected token`), but,

```
  moduleNameMapper: {
    '^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
  },
```

can fix the problem. I'm not sure the reason.

**Comment by eddyerburgh** [comment]
Can you post the repo where this didn't work?

**Comment by jonasohrn** [comment]
Also works for me only when put in moduleNameMapper like above.
The error was on this import:
`import 'font-awesome/css/font-awesome.min.css';`
in a dependent component in .vue file.

**Comment by eddyerburgh** [comment]
Can you please post a runnable example @jonasohrn, then I can update the README with a fix

**Comment by jonasohrn** [comment]
The same line in jest config as above fixed my problem which is unrelated to storybook:
moduleNameMapper: {
    '^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
  },
This was for the general problem that jest does not handle import of external css and I guess we need this stub both for local css (using transform config) but also add it to moduleNameMapper to stub transitive source dependencies imported css:
myTest -> myComponent.vue -> import otherLibraryComponent.vue -> "import some.css"

**Comment by angeliski** [comment]
Hey @jonasohrn Worked perfectly!

@eddyerburgh I created a simple repo to provide a example.

https://github.com/angeliski/jest-transform-stub-css-import

Maybe we can put some FAQ section in the README, what do you think?

**Comment by eddyerburgh** [comment]
Thanks for the reproduction 😄 

Jest doesn't apply transforms to node_modules by default. You can solve this by ignoring node_module transforms for js files only:

```js
{
  jest: {
    // ..
    "transformIgnorePatterns": ["/node_modules/.+\\.js$"]
  }
}

Or adding to `moduleNameMapper` as you have suggested:

```js
{
  jest: {
    "moduleNameMapper": {
      '^.+\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
    },
  }
}
