### ISSUE TITLE
Images are stubbed as Objects instead of Strings

### ISSUE THREAD

**Issue by jonaskuske** [eddyerburgh/jest-transform-stub#2]
When importing an image, the import returns an empty `Object` instead of a an empty `String`.
This causes issues with prop type validation / type checking.

I don't understand how it's happening as all the `index.js` of this package does is return `''`, but well, here's a normal Vue CLI 3 setup with jest enabled and the prop type is `object`: https://github.com/jonaskuske/jest-transform-stub-issue

**Comment by eddyerburgh** [comment]
Under the hood Jest has its own module resolving system, which is similar to commonjs. An imported module is an exports object, which in the case of an empty module is an empty object.

We could fix this in the transformer by adding this code:

```js
module.exports = {
  process: function() {
    return { code: 'module.exports = ""'}
  }
}
```

If we did that, we should also include a check for the filetype to determine whether the export should be a string or not. 

But for the moment I don't see a compelling reason to change the behavior, in your case you could simply create a mock string rather than import a file to use as the mock value.

**Comment by jonaskuske** [comment]
I see, thanks a lot for the explanation!


As for creating the mock string, I'd have to create it inside my component logic where I use it, right?
To clarify, I'd have to change this:

```js
import defaultImage from '@/images/img.png'

// ...
props: {
  backgroundImage: { type: String, default: defaultImage }
}
```
to this:
```js
const isTest = process.env.NODE_ENV === 'test'
// ...
props: {
  backgroundImage: { type: String, default: isTest ? '' : defaultImage }
}
```
Otherwise, every test that renders the component somewhere in the tree without passing an explicit image will bug me about the wrong prop type. (possibly multiple times)

**Comment by eddyerburgh** [comment]
You could pass it in as a prop in the test:

```js
const wrapper = shallowMount(HelloWorld, {     
  propsData: { msg, image: 'some-string' }
});
```

**Comment by jonaskuske** [comment]
Yep, I had the same problem – when testing the component itself, passing some `propData` within the test works, but when the component appears somewhere in the render tree you're still stuck with the prop type problem.

I'm now doing what I described in my comment above:
```javascript
const isTest = process.env.NODE_ENV === 'test'
const defaultImage = require('@/assets/image.jpg')
…
props: {
  backgroundImage: {
    type: String,
    default: isTest ? '' : defaultImage
  }
}

```

but you could probably also change accepted propTypes in test environments, which might be easier with your setup:

```javascript
props: {
  src: {
    type: isTest ? [String, Object] : String,
    required: true,
  }
}
```

&nbsp;  
...but all of this is ugly and shouldn't be needed 😅

**Comment by eddyerburgh** [comment]
2.0.0 now stubs as an empty string by default 👍

**Comment by daneah** [comment]
Thanks for the help @jonaskuske, and thanks for reacting quickly to that @eddyerburgh! I'll give 2.0 a try 😄

**Comment by simianarmy** [comment]
I installed 2.0.0 and still getting the prop type error when running tests with assets imported

```Error: Uncaught [Error: Warning: Failed prop type: Invalid prop `worldImg` of type `object` supplied to `StageCard`, expected `string`.
```

**Comment by simianarmy** [comment]
👆 Ignore the last comment, I fixed it
